NilsBrause/waylandpp

include/wayland-client.hpp
src/wayland-client.cpp

There are valid use cases for clients wanting to use the
underlying wl_proxy* of a proxy_t and there should be no particular
reason to deny them access to it. Also, since the proxy_t knows whether
it currently wraps any object, this should also be made available to
clients. Functionality for explicitly releasing the proxy can also
be useful.
The new functions have the prefix "proxy_" in order to minimize the
chances of name clashes with Wayland interface functions.

Allow public access to proxy_t c_ptr() and state

---

src/wayland-client.cpp

It is not an error to copy a proxy_t object that is empty.
It is in fact necessary for passing NULL objects to calls that
expect object ids such as wl_pointer::set_cursor.

Allow copying of empty proxy_t

---

example/SConstruct
example/dump.cpp
scanner/scanner.cpp

The scanner operated under the assumption that enums always get sent as uint32_t, which is not the case. Wayland wire protocol specifies that "the enum attribute can be used on either uint or int arguments."
I've added the `dump` example to show the error in action. It will crash if you try to run it without the scanner fix.

Fix enum protocol type

---

include/wayland-client.hpp
src/wayland-client.cpp

Customized reading from display file descriptors requires calling
wl_display_prepare_read and then either wl_display_cancel_read or
wl_display_read_events as pair, which is a prime candidate for
modeling with RAII in C++ as to not forget about cancelling
the read intent when leaving scope.

Introduce read_intent for announcing FD read intent with RAII

---

include/wayland-client.hpp
src/wayland-client.cpp

C library sometimes logs important information that should also be made available to the C++ code (with some added convenience).

Add wayland::set_log_handler

---

include/wayland-client.hpp
include/wayland-egl.hpp
src/wayland-client.cpp
src/wayland-egl.cpp

Now that `proxy_t` has `c_ptr()` public, it's only natural to add it here, too.
Also, if conversion operators to the native C types are defined, the C++ overloads for eglGetDisplay and eglCreateWindowSurface are not needed at all.
The conversion operators could theoretically be added to all other types, too - what do you think?

Reorganize EGL stuff

---

include/wayland-client.hpp
scanner/scanner.cpp
src/wayland-client.cpp

waylandpp currently segfaults when the code does this (happens e.g. when dispatching events with NULL objects):
```
wayland::proxy_t proxy;
wayland::surface_t(proxy);
```

Fix empty instance creation from proxy

---

include/wayland-client.hpp
src/wayland-client.cpp

`operator++` on unsigned int is by default not atomic, which means
that the refcount on proxy_t could be wrong when copying objects
in multiple threads at the same time. Fix by replacing with std::atomic.

Improve thread-safety when copying proxy_t

---

include/wayland-client.hpp
include/wayland-util.hpp
src/wayland-client.cpp
src/wayland-util.cpp

I think that a native-like C++ interface should really throw exceptions and not just pass around the error return values of the C API.

Throw std::system_exception when display_t operations fail

---

example/dump.cpp
include/wayland-client.hpp
scanner/scanner.cpp
src/wayland-client.cpp

- Use versioned constructor for objects bound using `registry_t::bind()` so `get_version()` actually returns something
- Add helpers that quickly check whether functions are available with the currently bound version
(this includes changes from #17 because I need the const `get_version`, can rebase if merged)

Add helpers for checking availability of functions

---

include/wayland-util.hpp
scanner/scanner.cpp
src/wayland-client.cpp
src/wayland-util.cpp

So users do not have to call the C API functions wl_fixed_... directly.
Giving implicit conversion operators means that event handlers can
receive an int or double as they please and it will automatically be
converted correctly.

Introduce wrapper for wl_fixed_t

---

src/wayland-client.cpp

Otherwise users can never set objects back to the default queue.
(c_ptr() throws on empty objects)

Accept empty event_queue_t for proxy_t::set_queue

---

include/wayland-client.hpp
src/wayland-client.cpp

Some objects (most notably: buffers from libwayland-cursor) are created
in other libraries and we just wrap them so they can be used as
arguments.
Previously, they would have the special parameter dontdestroy set so
that they would not be destroyed if the waylandpp proxy goes out of
scope since the library that owns them would get into trouble then.
But this is not enough: If the waylandpp proxy is destroyed and events
happen after that, the original library will not get them since we
have added our dispatcher. And worse than that, our dispatcher will
crash since the C++ wrapper does not exist any more.
So to fix this, change "dontdestroy" to proper "foreign": If foreign is
set, it means that another library is responsible and we should neither
add our dispatcher nor destroy the object …

Fix handling of objects that are owned by other libraries

---

example/SConstruct
example/proxy_wrapper.cpp
include/wayland-client.hpp
scanner/scanner.cpp
src/wayland-client.cpp
src/wayland-cursor.cpp

One of the last features of libwayland-client that waylandpp does not support are proxy wrappers - so this PR adds them.
Proxy wrappers are necessary when multiple threads share one Wayland connection, as can easily be the case in multi-threaded Wayland clients. There is a demo program included that shows that not using proxy wrappers for e.g. getting globals will result in failure.
To test the failure, I use `./proxy_wrapper 15 100000 0` which fails after some 10000 iterations, but as usual for races ymmv.

Add support for proxy wrappers

---

scanner/scanner.cpp

I think this got unintentionally broken in 7b4307eb88aa1cfa42ea3f64aaff16cfcbf446aa
Effect is similar to #2

Support NULL proxies as arguments

---

include/wayland-cursor.hpp
include/wayland-util.hpp
src/wayland-cursor.cpp

None of those functions logically modify the cursor/cursor theme, so
they should be marked constant.

Make cursor methods const

---

CMakeLists.txt

wayland-client-extra++ was missing a dependency on
wayland-client-protocol.hpp, causing build errors. wayland-version.hpp
on the other hand does not need to be mentioned because wayland-client++
installs it already.
@NilsBrause would be cool if you could release this as 0.2.1

[CMake] Fix wayland-client-extra++ dependencies

---

CMakeLists.txt

wayland-client-extra++ uses nonexistant cflags/libs. This causes an issue on OpenSUSE where wayland headers are installed to `/usr/include/wayland` (different from pretty much all other distributions) and son compilation without the correct cflags does not work.
See https://github.com/hudokkow/xbmc/pull/2#issuecomment-382131123

Fix compilation on OpenSUSE

---

CMakeLists.txt

It currently sometimes fails to build on FreeBSD. This seems to fix it.
```
[ 72%] Building CXX object CMakeFiles/wayland-client-unstable++.dir/wayland-client-protocol-unstable.cpp.o
/usr/bin/c++  -Dwayland_client_unstable___EXPORTS -I/wrkdirs/usr/ports/graphics/waylandpp/work/waylandpp-0.2.4/include -I/wrkdirs/usr/ports/graphics/waylandpp/work/.build -O2 -pipe -fstack-protector -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -fPIC   -I/usr/local/include -std=gnu++11 -o CMakeFiles/wayland-client-unstable++.dir/wayland-client-protocol-unstable.cpp.o -c /wrkdirs/usr/ports/graphics/waylandpp/work/.build/wayland-client-protocol-unstable.cpp
In file included from /wrkdirs/usr/ports/graphics/waylandpp/work/.build/wayland-client-protocol-unstable.cpp:1: …
```

Add missing ${PROTO_FILES_EXTRA} dependency to ${PROTO_FILES_UNSTABLE}

---

CMakeLists.txt

Some of the libraries need to link to the just built libraries of the
project, instead of stale versions that may exist in the system.
Since the helper function define_library does not support additional
arguments due to the usage of ARGN, append the required
target_link_libraries call to make cmake aware of the build dependency.
Signed-off-by: Olaf Hering <olaf@aepfle.de>

link to current libraries

---

wayland-client++.pc.in
wayland-cursor++.pc.in
wayland-egl++.pc.in

The exported header files require headers from foreign packages
Show their required cflags in pkgconfig --cflags output so that
consumers of our pkgconfig files get the all the required options.
Signed-off-by: Olaf Hering <olaf@aepfle.de>

include path the foreign header files in pkgconfig

---

CMakeLists.txt

The documentation of cmake 3.3 and later suggests to call
cmake_minimum_required() before project().
This change does not fix any issue I have encountered. It is supposed to
be a cosmetic change to follow documentation of project() usage.
Signed-off-by: Olaf Hering <olaf@aepfle.de>

Set expected cmake version before project

---

CMakeLists.txt
waylandpp-config.cmake.in

As indicated in #60, this adds the option to build the libraries static, and adds CMake-Config files.
Using the static libs with pkg-config will likely still need the libwayland dependencies to be manually added to the linker flags.
Some boilerplate CMake stuff got changes where necessary,
the basic idea is to use
```cmake
find_package(Waylandpp)
...
target_link_libraries(example PUBLIC|PRIVATE Waylandpp::wayland-egl++)
```

Build static libs and cmake config

---

include/wayland-util.hpp

fixes `error: ‘runtime_error’ is not a member of ‘std’`

[fix] add missing stdexcept include after 2d834a6

---

CMakeLists.txt

These protocols are labelled as unstable but any breaking changes upstream
will change the _v suffix on the types anyway, so they're more stable
than most interfaces.
Nevertheless, hide it behind an option for those that really don't want them.
I wasn't sure if skipping the unstable protocols was intentional or just an oversight. If it was just an oversight, we can probably skip the option.

Install the unstable protocol headers as well

---

include/wayland-client.hpp
scanner/scanner.cpp

Upcoming `gcc-13` made `<string>` leaner and does not include `<cstdint>` implicitly anymore. As a result build fails without the change as:
[  2%] Building CXX object CMakeFiles/wayland-scanner++.dir/scanner/scanner.cpp.o
scanner/scanner.cpp:378:3: error: 'uint32_t' does not name a type
378 |   uint32_t width = 0;
|   ^~~~~~~~

add missing <cstdint> include

---

example/dump.cpp
example/egl.cpp
example/pingpong.cpp
example/proxy_wrapper.cpp
example/shm.cpp
scanner/scanner.cpp

I had some instabilities when I run a simple wayland client using waylandpp libraries on several platforms with different desktop environments. I am not sure if it is related but when compiled interface version (such as wl_output) is greater than the one used by the compositor at run-time, I had sometimes an exception that rises up.
This patch does not fix any problem but it allows me to target with more accuracy static and dynamic version currently in use.
Related to this issue: https://github.com/NilsBrause/waylandpp/issues/77

[scanner] Create static member for each interface to get static version

---

CMakeLists.txt

If you are using the lib on a machine other than the one using to compile the lib, it may be useful to redefine the prefix of `.pc` files

[cmake] Allow the .pc prefix to be redefined
